alias g=git
alias gr='cd $(git rev-parse --show-toplevel)'
alias ll='ls -FGlAhp'
alias k='kubectl'
alias n=nvim
alias nn=nvim-nightly
alias pn=pnpm
alias t=tmux
alias tx=tmuxinator

alias -g gp='| grep -i'

setopt autocd

alias d='dirs -v'
setopt autopushd
setopt pushdsilent
setopt pushdminus
DIRSTACKSIZE=10

# Case insensitive completion
# zstyle ':completion:*' matcher-list 'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*' 'm:{[:lower:][:upper:]}={[:upper:][:lower:]} l:|=* r:|=*'
# zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'

autoload bashcompinit && bashcompinit
autoload -Uz compinit && compinit

autoload -Uz vcs_info
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:git*' formats " (%b)"
zstyle ':vcs_info:git*' actionformats " (%b | %a)"
precmd() {
    vcs_info
}

# Prompt
# setopt prompt_subst
# export PROMPT='%n: %~${vcs_info_msg_0_}%# '
# export RPROMPT=''
autoload -U promptinit; promptinit
prompt pure

# vi mode
bindkey -v
export KEYTIMEOUT=1

# History settings
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=${ZDOTDIR:-$HOME}/.zsh_history
unsetopt SHARE_HISTORY
setopt APPEND_HISTORY
unsetopt INC_APPEND_HISTORY

setopt HIST_IGNORE_DUPS
setopt HIST_REDUCE_BLANKS
setopt HIST_IGNORE_SPACE

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey '^[[A' up-line-or-beginning-search
bindkey '^[[B' down-line-or-beginning-search

function append-help() {
  LBUFFER="$LBUFFER --help"
  zle redisplay
}
zle -N append-help
bindkey '^h' append-help

export ZSH_AUTOSUGGEST_STRATEGY=(completion)

[ -n "${commands[direnv]}" ] && eval "$(direnv hook zsh)"
[ -n "${commands[fnm]}" ] && eval "$(fnm env --use-on-cd --corepack-enabled --version-file-strategy=recursive)"
[ -n "${commands[fzf]}" ] && source <(fzf --zsh)

[ -f ~/.ghcup/env ] && source ~/.ghcup/env
[ -f ~/.utils.sh ] && source ~/.utils.sh

[[ ! -r ~/.opam/opam-init/init.zsh ]] || source ~/.opam/opam-init/init.zsh  > /dev/null 2> /dev/null
[ -f ~/.sdkman/bin/sdkman-init.sh ] && source ~/.sdkman/bin/sdkman-init.sh

[[ ! -r /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]] || source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh  > /dev/null 2> /dev/null
