name: CI

on: [push]

permissions:
  contents: read

jobs:
  stylua:
    name: Check formatting
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - uses: JohnnyMorganz/stylua-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 0.16.1
          args: --check nvim/

  luacheck:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
          sudo luarocks install luacheck

      - name: Lint
        run: luacheck nvim/

  test:
    name: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y luarocks
          sudo luarocks install busted

      - name: Test
        run: busted nvim/lua -lpath='./nvim/lua/?.lua'
